#spring.application.name=usersApiTask

age.minimum: 18

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/krasnopolskyi_task_users_api?createDatabaseIfNotExist=true
    username: root
    password: root

